name: Deploy Node App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Save SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > devops-key.pem
          chmod 600 devops-key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i devops-key.pem ubuntu@16.171.27.119 << 'EOF'

          # Stop & remove old container if exists
          docker stop devops-node-server || true
          docker rm devops-node-server || true

          # Remove old folder to ensure fresh clone
          rm -rf CI-CD-Pipeline
          git clone https://github.com/ngollodev/CI-CD-Pipeline.git
          cd CI-CD-Pipeline

          # Build Docker image using your Dockerfile
          docker build -t node-backend:v1 .

          # Run container
          docker run -d -p 3000:3000 --name devops-node-server node-backend:v1

          EOF